#DNA count
#방법 1
sampledata = 'ACGGGGTCTTTCGAGATAATTCGGCCCACATTTATCGTGGTATAATCAAAAACTAGACTGATATGGGGGGATCCCCGACTCTACGGGCGGATAAGTGCTGTGCTTCCTCGTTCAACTTCGGGTATGCGCGACGTACTCTTCGCTATAAGGCCTGATCAAACCTCCCTGAGTGACACATTGGTTGCTTGATTTTATTCCCTATATTGTACTATACCAATAGAAGTTACTCCTAAATAACAATTCATCTAGCAGAGAACTAGATCTTTGGCGTCGGAGCGAAGGTTCACGTGTTACAGACACAATTCGCATTGCTGAACCAGACTGAGCTTGTTATTAAGGACGAACTAATCTATCGGAAGCCAGTTGCTTATCTTCGGAGGAATGTTTCATTGATTTTCGCCCTCCGTTGTTCACTTCGTATCAGACTGTGTAACATGGGAGAGCTGTGTCAGTTCTGCGCGACACAGCGGTCAGTGTAGCTGTTAGCGAGTGAGCCCCCTGGCTCCAAAGAGTCGTGCACTGAAAGGTAATCCACCTCTATGAATGGTCATGCAAGTAGCCGCGAGACCAGAGCCAAGCCTCTTCCCGGTGTCTCTGTTGGGAGGTCAGAGGCTAACGGGAAATGAGATTATCGTTCGAGCAGGCAAAATGTGGGAGTACTTAAAACGAGGTATAAAAGCCTATTGTGAAACGAATGCATGCAAAGCACCATGTTCAAAGGATGAAGGGCTCTCATGCGAAGAGTAGTTCACATTTTCGGCACCTTTTATTGCGAGCAAAATCAGCACAAAGGATTGCTTGGGTATAACCGAGTGGACTGTTGCCT'

list_data = list(sampledata)
A, G, C, T = 0, 0, 0, 0
for i in list_data : 
    if i == 'A' : 
        A += 1
    elif i == 'G' : 
        G += 1
    elif i == 'C' : 
        C += 1
    else : T += 1
    
answer = f'{A} {C} {G} {T}'
print(answer)

#방법2
dic = {'A' : 0, 'C' : 0, 'G'  : 0, 'T' : 0}
for i in dic.keys() : 
    dic[i] = sampledata.count(i)
count_list = dic.values()
answer = ' '.join(map(str, count_list))
print(answer)
