#Finding a Motif in DNA

def find_string(string_1, string_2) : 
    list_string = [string_1[i : i + len(string_2)] for i in range(0, len(string_1))]
    matched_pos = []
    for j in range(0, len(list_string)) : 
        if list_string[j] == string_2 : 
            matched_pos.append(str(j + 1))
        else : continue
    
    matched = ' '.join(matched_pos)
    
    return(matched)


string_1 = 'GAAAGCGGTGCAGCGGTGCAAGCGGTGTTAGCGGTGGGCCAGGGGTGAGGAATGCAGCGGTGAGCGGTGAGAGGAGAGCGGTGCAGCGGTGTTGAGCGGTGAGCGGTGGTGCAGCGGTGTGAGCGGTGAGCGGTGGAAGCGGTGAGCGGTGCTAGCGGTGCAGCGGTGTCAAAAGCGGTGAGCGGTGAGCGGTGGTGGAGCGGTGAAATAGCGGTGAGCGGTGAGAACAGCGGTGAGCGGTGAGCGGTGAGCGGTGCACGCGTCTTCTAGCGGTGTTCGGGGACGTGAGCGGTGCAGCGGTGTTACAGCGGTGAGCGGTGCGAAGCGGTGTAGCGGTGTAGCGGTGTCGGGCATAGCGGTGGCAGCGGTGAAGCGGTGTCAGCGGTGGGTTAGCGGTGACCAGCGGTGAGCGGTGAGCGGTGGGGCCTTCTAGCGGTGACTTCCAGCGGTGTACAGCGGTGGAGCGGTGAGCGGTGGCTTGTAGCGGTGCCTTTTAGCGGTGGAGCTAGCGGTGCGCAGCGGTGAAGCGGTGAGCGGTGTAGCGGTGGATAAGCGGTGTGATCTGAGCGGTGAGCGGTGAAAGCGGTGAGCGGTGAATGTAAGCGGTGAGCGGTGAGCGGTGCCGTAGCGGTGAGCGGTGTGCGAGCGGTGCAGCGGTGCAGCGGTGAGCGGTGAAGCGGTGAGCGGTGAGCGGTGAAGCGGTGTAAGCGGTGACAGCGGTGGTAGCGGTGTTACAGCGGTGCCGAGCGGTGGGTGTCCCGAGCGGTGAAGCGGTGAGCGGTGAGCGGTGTGCCAGCGGTGTATAAGCGGTGTAGCGGTGAGCGGTGCCAGCGGTG'
string_2 = 'AGCGGTGAG'


find_string(string_1, string_2)
