#introduce bioinformatics

def count_ACGT(sequence) : 
    n_A, n_C, n_G, n_T = 0, 0, 0, 0
    s_list = list(sequence)
    for i in s_list : 
        if i == 'A' : 
            n_A += 1
        elif i == 'C' : 
            n_C += 1
        elif i == 'G' : 
            n_G += 1
        else : 
            n_T += 1
    return n_A, n_C, n_G, n_T


sequence = 'AGTTGTATGGGGGGGTAGGCAGCCCAGTGTGTGAGGTAAATTCTCGTAGCAGCTCAGCGATTGCTGTCCTTGTCTACGTCTGACTATTGTTTGGACAGGTACAGACACATCGAATAATGATACTACTACTGGGACCGATCCTTGTTAGCGCACGTGCCCGAACCTCGAAGACACCTCCGTGAAGTAGCATGTGGCGATTACAGAGTTGGCTTGTGTATCCTCTATTGAGCCACTATCGTATTGAACTCGAAACTAATACCTGATCCAACACCGTTCTGGGAAAGATGATGTACAGAAGTAAAGTGCAACAGGTTACAGCCTTACTGTTCCACTTCGGCGGGGCGAGACTCTGCATTGTTTCTGTAGCTGGTCATTCCTACACGCTCGAAAGATTGAAGTAGCGCATACTTAAGCCTATTAGTGCAACGTTCATAAGCATGTCCATTATCCGCTTGATATAGAATAGGTTCTACGTTAGGTGGAGGGTTCAATCAGGGTCTATCTCCTAAAATCCTTAAAGTCTTTTCCCGATGTCTTGTGACGCTCGCCGACCAACAGTTTTTATATTTCAGCCGCGTCCAGACTTCACGTCCAATGCCCAATCATGAACGCATTGAGTTGCAGTTTTTCGGTCCTTTTATAGTCACTTAATCATGTCCCGAGGTATCACGCCGGACTCCTTAAGTTCCGGGACAGCGTGGAATGCTGATTATGCGATCATCGTTTTTCGCCTTTTTCCGACGTGACCATCTAAGTGTCAGAAAACACCTTTACCGGCAGGAGGGACAGTTTCGTGGCAACATAAGGGTTCCTATAGCTGCAGCGATACGCCTTTCGTAGGTCAAG'

a, b, c, d = count_ACGT(sequence)

print(f'{a} {b} {c} {d}')
