#RNA
sampledata = 'CTGTAATAAAAGCTATCGAGATTGCATCTATGTCAACAACCAGGCGCATAGCAGGGCGAAGTTTCTTACGATGATCCCTAAGCGGAAGCTGGTCCTGACTACTTTTCGCCACGGGCGACGGCTCTCAGATAATCGATTGCCCACCAGAGGCCAGAAAAACGGAGCCAGGCCCACTTCCTGAAAGACGCGTGATTTCGACAAGGGACTGCCTGCGCACGACCCCCTCCATGGCCACGCCCGCTCCTATGCGACTACGTGGAGCATTGTGCGCGGTGCTGGACCCCAAAGAGGTCGTTCTATGCCAAGGGGGGAGATTATAAGGAATAGGATGGATGTGGGACAACGGGAAACAGATCCAAATAAGCTTACTGAAGGATGACACTCCTTGAGCAGAAAATAGGCGCTCTGGCCGATGGACACAGGAGACAACTGTCAGTAACCTTGGCCAACAATAATGCGGGTGTTCAATCCAAATCTCAAAGGAGTCAAGGGGGGGCTTCCCTAGGAAGTCCTTTGCTAGTCATCTTGGAGTGTTCGTCTAAGGAGCCTAGGAAACCTTTTGACAACGATCGAATAAAAGGAGGCAATGTTAGGGGAGAGTCAAGTTCGGATTACATGCATCGGTCCGTATGTGTTTATGCACCGTATACATTACCTCAGGAATGCGCAGTATCATGCCGAGGCCTGCTCACTACTGTAGGCGGCGAGAATGACTGGCCCGCTACCGCGTGGAAGCGCTTTTGAGTTTGGTACCAACTCTTCCTACCGTCCAGTCAAGACAGCATGGGACAGAACTAAACTACTGCTAACTATGGATCAGGTGGCGGTCGTTGTCTGCCGGAGCAGATGATGATGTCGGGGCATTCAAGCAGTAGGAAACATAGGATATGTCTGACCAATTATTCATCTCGTCCTGTCAAGATCCCGGAGACTGACATATTA'
list_data = list(sampledata)

def to_RNA(code) : 
    if code == 'T' : 
        code = 'U'
    else : 
        code = code
        
    return code

lists = []
for i in list_data : 
    lists.append(to_RNA(i))
answer = ''.join(lists)
print(answer)
